[ui]
agent_panel_sort = "spaces"

[keys]
prefix = "ctrl+j"
navigate_workspace_down = "j"
navigate_workspace_up = "k"

[ui.toast]
delivery = "herdr"

[experimental]
pane_history = false

[theme]
name = "tokyo-night"
auto_switch = false
