set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g pane-border-status off
set -g status-style fg=white,bg=black
set -s copy-command 'pbcopy'
set -sg escape-time 100
set -g allow-passthrough on
set -g focus-events on
set-window-option -g mode-keys vi
set -g prefix C-j
unbind C-b
bind C-j send-prefix

bind r source-file ~/.tmux.conf \; display "Reloaded"

set -g status-interval 1
set -g status-left-length 80
set -g status-left "#[fg=cyan]#(${HOME}/.tmux/scripts/tmux-status-git.sh)#[fg=white]| "
set -g status-right-length 50
set -g status-right \
"#{?client_prefix,#[reverse],}"\
"#[fg=cyan][%Y-%m-%d(%a) %H:%M:%S]"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
